**What is Computer Vision ?**

- Computer Vision is a field that care about how computers can gain a high-level understanding from digital images/videos. It is an attempt to automate tasks that the human visual system is able to perform. This is a process of **acquiring, processing, analyzing, and understanding digital images, and extracting high-dimensional data from the real world (to produce numerical/symbolic information.)**



- Typical tasks involved Python Computer Vision are:
    - Recognition
    - Motion Analysis
    - Scene Reconstruction
    - Image Restoration


**What is  OpenCV ?**

- **Gary Bradsky** started OpenCV at Intel in 1999. While it supports languages like C++, Python, and more, and OpenCV-Python is an API for OpenCV to unleash the power of Python and the OpenCV C++ API at once.

- Python-OpenCV is just a wrapper around the original C/C++ code. It is normally used for combining best features of both the languages, **Performance of C/C++** & **Simplicity of Python**.

- OpenCV (Open Source Computer Vision Library) is an open source computer vision and machine learning software library.This library uses **NumPy** and all its array structures convert to and from **NumPy arrays**. This also means we can integrate it easily with other libraries like **SciPy** and **Matplotlib (these make use of NumPy)**.

- The library has more than 2500 optimized algorithms, which includes a comprehensive set of both classic and state-of-the-art computer vision and machine learning algorithms.

**Installing OpenCV in Python**


- Before you can install OpenCV, make sure you have **Python** and **NumPy** installed on your machine.
- Use Script to install OpenCV  **`pip install opencv-python`**. 

**Load an Image** 

In [1]:
import cv2 ### Load opencv 

image = cv2.imread('images/1.jpg') ### returns a NumPy array representing the image.
cv2.imshow("test", image) ### display the image in a window
cv2.waitKey(0) ### pauses the execution of the script until we press a key on our keyboard
cv2.destroyAllWindows()

If everything has worked correctly, you should see your image in  window.

**Image Basics**

The basic building block of image is yes you guessed it right it's pixels. 

- What is a Pixel ?
    - Normally, we think of a pixel as the **color** or the **intensity** of light that appears in a given place in our image.
    
    - If we think of an image as a grid, each square in the grid
        contains a single pixel.
    - Most pixels are represented in two ways: grayscale and
        color. 
     - In a grayscale image, each pixel has a value between
        0 and 255, where zero corresponds to “black” and 255 corresponds
        to “white”. The values in between 0 and 255 are
        varying shades of gray, where values closer to 0 are darker
        and values closer to 255 are lighter.
      - Color pixels are normally represented in the RGB color
        space – one value for the Red component, one for Green,
        and one for Blue.
      - We then combine these values into an RGB tuple in the
        form (red, green, blue). This tuple represents our color.

- Coordinate System
    - As I mentioned above, an image is represented as a grid of
pixels. Imagine our grid as a piece of graph paper. Using
this graph paper, the point (0, 0) corresponds to the upper
left corner of the image. As we move down and to the right,
both the x and y values increase.

**Accessing and manipulating pixels**

In [3]:
image = cv2.imread('images/1.jpg')
print(image)
(b, g, r) = image[0, 0]
print("Pixel at (0, 0) - Red: {}, Green: {}, Blue: {}".format(r,g, b))

image[0, 0] = (0, 0, 255)
(b, g, r) = image[0, 0]
print("Pixel at (0, 0) - Red: {}, Green: {}, Blue: {}".format(r,g, b))

[[[ 28  35  30]
  [ 27  34  29]
  [ 25  32  27]
  ...
  [  7   7   7]
  [  7   7   7]
  [  7   7   7]]

 [[ 28  35  30]
  [ 27  34  29]
  [ 25  32  27]
  ...
  [  7   7   7]
  [  7   7   7]
  [  7   7   7]]

 [[ 26  36  30]
  [ 25  35  29]
  [ 23  33  27]
  ...
  [  7   7   7]
  [  7   7   7]
  [  7   7   7]]

 ...

 [[ 99 106 101]
  [ 98 108 102]
  [100 107 102]
  ...
  [ 92 104  98]
  [ 92 104  98]
  [ 92 104  98]]

 [[100 106 101]
  [ 99 106 101]
  [100 106 101]
  ...
  [ 91 103  97]
  [ 91 103  97]
  [ 91 103  97]]

 [[100 106 101]
  [100 106 101]
  [100 106 101]
  ...
  [ 91 103  97]
  [ 91 103  97]
  [ 91 103  97]]]
Pixel at (0, 0) - Red: 30, Green: 35, Blue: 28
Pixel at (0, 0) - Red: 255, Green: 0, Blue: 0


In [4]:
corner = image[0:100, 0:100]
cv2.imshow("Corner", corner)

image[0:100, 0:100] = (0, 255, 0)
cv2.imshow("Updated", image)

cv2.waitKey(0)
cv2.destroyAllWindows()

**Drawing in OpenCV** 

Using NumPy array slices we were able to
draw a green square on our image. But what if we wanted
to draw a single line? Or a circle? NumPy does not provide
that type of functionality – it’s only a numerical processing
library after all!


Luckily, OpenCV provides convenient, easy-to-use methods
to draw shapes on an image.We’ll review
the three most basic methods to draw shapes: 
`cv2.line`, `cv2.rectangle`, and `cv2.circle`.

In [5]:
import numpy as np


canvas = np.zeros((300,300,3))

red = (0,0,255)
green = (0,255,0)
blue = (255,0,0)

cv2.line(canvas,(0,0),(300,300),green)
cv2.imshow('Canvas',canvas)

cv2.line(canvas,(300,0),(0,300),blue,3)
cv2.imshow('Canvas',canvas)

cv2.rectangle(canvas, (10, 10), (60, 60), green)
cv2.imshow("Canvas", canvas)

cv2.rectangle(canvas, (50, 200), (200, 225), blue, 5)
cv2.imshow("Canvas", canvas)


cv2.rectangle(canvas, (200, 50), (225, 125), red, -1)
cv2.imshow("Canvas", canvas)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
canvas = np.zeros((300, 300, 3))
(centerX, centerY) = (canvas.shape[1] // 2, canvas.shape[0] // 2)
white = (255, 255, 255)
for r in range(0, 175, 25):
    cv2.circle(canvas, (centerX, centerY), r, white)
cv2.imshow("Canvas", canvas)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
for i in range(0, 25):
    radius = np.random.randint(5, 200)
    color = np.random.randint(0,256, (3,)).tolist()
    pt = np.random.randint(0, 300,(2,))
    cv2.circle(canvas, tuple(pt), radius, color,-1)
    
    
cv2.imshow("Canvas", canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()

**Image Processing**

Now that you have a solid foundation to build upon, we
can start to exploring simple image processing techniques.
First, we’ll start off with basic image transformations,
such as **translation, rotation, resizing, flipping, and cropping**.


- **Translation**

    The first method we are going to explore is translation.
    Translation is the shifting of an image along the x and y
    axis. Using translation, we can shift an image up, down,
    left, or right, along with any combination of the above!

In [8]:
image = cv2.imread('images/1.jpg')
cv2.imshow('Image',image)

M  = np.float32([[1,0,25],[0,1,50]]) 
shifted = cv2.warpAffine(image,M,(image.shape[1],image.shape[0]))
cv2.imshow('shifted down and right',shifted)

M  = np.float32([[1,0,-50],[0,1,-90]]) 
shifted = cv2.warpAffine(image,M,(image.shape[1],image.shape[0]))
cv2.imshow('shifted up and left',shifted)

cv2.waitKey(0)
cv2.destroyAllWindows()

- **Rotation**

Rotation is exactly what it sounds like: rotating an image
by some angle q. In this section, we’ll explore how to rotate
an image. We’ll use q to represent by how many degrees
we are rotating the image.

In [10]:
image = cv2.imread('images/1.jpg')
cv2.imshow('Original',image)

(h,w) = image.shape[:2]
center = (w//2,h//2)

M = cv2.getRotationMatrix2D(center,-45,1.0)
rotated = cv2.warpAffine(image,M,(w,h))

cv2.imshow('Rotated by 45 degrees',rotated)

cv2.waitKey(0)
cv2.destroyAllWindows()

- **Resizing**

So far we’ve covered two image transformations: translation
and rotation. Now, we are going to explore how to
resize an image.

In [11]:
image = cv2.imread('images/1.jpg')
cv2.imshow('Original',image)

r = 150.0/image.shape[1]
print(r)
dim = (150,int(image.shape[0]*r))

resized = cv2.resize(image,dim,interpolation = cv2.INTER_AREA)
cv2.imshow('Resized Image',resized)


cv2.waitKey(0)
cv2.destroyAllWindows()

0.5791505791505791


- **Flipping**

Next up on our image transformations to explore is flipping
an image. We can flip an image around either the x or
y axis, or even both.

In [12]:
image = cv2.imread('images/1.jpg')
cv2.imshow('Original',image)


flipped = cv2.flip(image, 1)
cv2.imshow("Flipped Horizontally", flipped)

cv2.waitKey(0)
cv2.destroyAllWindows()

- **Cropping**

When we crop an image, we want to remove the outer parts
of the image that we are not interested in. We can accomplish
image cropping by using NumPy array slicing.

In [13]:
image = cv2.imread('images/1.jpg')
cv2.imshow('Original',image)

cropped = image[0:100,0:100]
cv2.imshow("Cropped", cropped)

cv2.waitKey(0)
cv2.destroyAllWindows()

**Smoothing and Blurring**

- I’m pretty sure we all know what blurring is. It’s what
    happens when your camera takes a picture out of focus.
    Sharper regions in the image lose their detail, normally as
    a disc/circular shape.

- Practically, this means that each pixel in the image is
    mixed in with its surrounding pixel intensities. This “mixture”
    of pixels in a neighborhood becomes our blurred pixel.
    
    
- While this effect is usually unwanted in our photographs,
it’s actually quite helpful when performing image processing
tasks.
In fact, many image processing and computer vision functions,
such as thresholding and edge detection, perform better
if the image is first smoothed or blurred.

- **Averaging**

The first blurring method we are going to explore is averaging.
       
As the name suggests, we are going to define a k x k sliding
window on top of our image, where k is always an odd
number. This window is going to slide from left-to-right
and from top-to-bottom. The pixel at the center of this matrix
(we have to use an odd number, otherwise there would
not be a true “center”) is then set to be the average of all
other pixels surrounding it.
We call this sliding window a “convolution kernel” or
just a “kernel” 

In [14]:
import numpy as np
image = cv2.imread('images/1.jpg')
blurred = np.hstack([cv2.blur(image, (3, 3))])
cv2.imshow('Blurred',blurred)
cv2.waitKey(0)
cv2.destroyAllWindows()

- **Gaussian**


- Next up, we are going to review Gaussian blurring. Gaussian
blurring is similar to average blurring, but instead of
using a simple mean, we are now using a weighted mean,
where neighborhood pixels that are closer to the central
pixel contribute more “weight” to the average.
- The end result is that our image is less blurred, but more
naturally blurred, than using the average method discussed
in the previous section

In [15]:
import numpy as np
image = cv2.imread('images/1.jpg')
blurred = np.hstack([cv2.GaussianBlur(image, (11,11),0)])
cv2.imshow('Blurred',blurred)
cv2.waitKey(0)
cv2.destroyAllWindows()

**Thresholding**


Thresholding is the binarization of an image. In general,
we seek to convert a grayscale image to a binary image,
where the pixels are either 0 or 255.
A simple thresholding example would be selecting a pixel
value p, and then setting all pixel intensities less than p to
zero, and all pixel values greater than p to 255. In this way,
we are able to create a binary representation of the image.
Normally, we use thresholding to focus on objects or areas
of particular interest in an image.

- **Simple Thresholding**

Applying simple thresholding methods requires human intervention.
We must specify a threshold value T. All pixel
intensities below T are set to 0. And all pixel intensities
greater than T are set to 255.

In [16]:
image = cv2.imread('images/2.jpg')
cv2.imshow('Original',image)
image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
blurred = cv2.GaussianBlur(image, (5, 5), 0)


(T, thresh) = cv2.threshold(blurred, 155, 255, cv2.THRESH_BINARY)
(T, threshInv) = cv2.threshold(blurred, 155, 255, cv2.THRESH_BINARY_INV)

cv2.imshow('Thresholding',threshInv)
cv2.waitKey(0)
cv2.destroyAllWindows()

- **Adaptive Thresholding**


One of the downsides of using simple thresholding methods
is that we need to manually supply our threshold value
T. Not only does finding a good value of T require a lot of
manual experiments and parameter tunings, it’s not very helpful if the image exhibits a lot of range in pixel intensities.

Simply put, having just one value of T might not suffice.
In order to overcome this problem, we can use adaptive
thresholding, which considers small neighbors of pixels
and then finds an optimal threshold value T for each neighbor.
This method allows us to handle cases where there
may be dramatic ranges of pixel intensities and the optimal
value of T may change for different parts of the image.

In [14]:
image = cv2.imread('2.jpg')

image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

blurred = cv2.GaussianBlur(image, (5, 5), 0)
thresh = cv2.adaptiveThreshold(blurred,255,cv2.ADAPTIVE_THRESH_MEAN_C,cv2.THRESH_BINARY_INV,11,4)

thresh = cv2.adaptiveThreshold(blurred, 255,
cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY_INV, 15, 3)

cv2.imshow("Gaussian Thresh",thresh)

cv2.waitKey(0)
cv2.destroyAllWindows()

**Gradients and Edge Detection**

This chapter is primarily concerned with gradients and
edge detection. Formally, edge detection embodies mathematical
methods to find points in an image where the
brightness of pixel intensities changes distinctly.

The first thing we are going to do is find the “gradient” of
the grayscale image, allowing us to find edge-like regions
in the x and y direction.


In [17]:
image = cv2.imread('images/2.jpg')
image = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
cv2.imshow('Original',image)

lap = cv2.Laplacian(image,cv2.CV_64F)

lap = np.uint8(np.absolute(lap))
cv2.imshow('Laplacian',lap)

cv2.waitKey(0)
cv2.destroyAllWindows()

**Canny Edge Detection**

In [18]:
image = cv2.imread('images/2.jpg')

image = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
image = cv2.GaussianBlur(image, (5, 5), 0)
cv2.imshow('Blurred',image)

canny = cv2.Canny(image, 30, 150)
cv2.imshow('Canny',canny)

cv2.waitKey(0)
cv2.destroyAllWindows()

**Contours**

Previously, we explored how to detect edges in an image
of coins.
Now we are going to use these edges to help us find the
actual coins in the image and count them.
OpenCV provides methods to find “curves” in an image,
called contours. A contour is a curve of points, with no
gaps in the curve. Contours are extremely useful for such
things as shape approximation and analysis.

In [19]:
image = cv2.imread('images/2.jpg')

gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
blurred = cv2.GaussianBlur(gray,(5,5),0)

edged = cv2.Canny(blurred,30,150)
cv2.imshow('Edge Detection',edged)


(cnts, _) = cv2.findContours(edged.copy(), cv2.RETR_EXTERNAL,
cv2.CHAIN_APPROX_SIMPLE)

print('I Count {} coins in this image'.format(len(cnts)))
coins = image.copy()

cv2.drawContours(coins,cnts,-1,(0,255,0),2)
cv2.putText(coins, '{} coins'.format(len(cnts)), (50, 50), cv2.FONT_HERSHEY_SIMPLEX,1,(0, 0, 255) , 5, cv2.LINE_AA) 
cv2.imshow('Coins',coins)


cv2.waitKey(0)
cv2.destroyAllWindows()

I Count 6 coins in this image


**Conclusion**

- We’ve explored many image processing and computer vision techniques, including basic image processing,such as translation, rotating, and resizing.

- Then moved on to blurring our images, using different methods,
such as averaging, Gaussian, and median filtering.

- We thresholded our images to find objects of interest,
then applied edge detection.

- Finally we learned how to use contours to count the number
of coins in the image.
